// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBORFU3zbtxQxcLidsWRzQ5-1KrKY3eRKI',
    appId: '1:585335891737:web:cdcc19a24ca94a60cd0788',
    messagingSenderId: '585335891737',
    projectId: 'bismillahh-3650a',
    authDomain: 'bismillahh-3650a.firebaseapp.com',
    storageBucket: 'bismillahh-3650a.appspot.com',
    measurementId: 'G-HE61GV87LW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcefBU2QmcjIIafgewuve80-yyWLPlbRQ',
    appId: '1:585335891737:android:91c6c086b6e6c352cd0788',
    messagingSenderId: '585335891737',
    projectId: 'bismillahh-3650a',
    storageBucket: 'bismillahh-3650a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpjDmFt5aEJpfy5sBYhT2HIHc30T_zWXI',
    appId: '1:585335891737:ios:ef010c3f7592b004cd0788',
    messagingSenderId: '585335891737',
    projectId: 'bismillahh-3650a',
    storageBucket: 'bismillahh-3650a.appspot.com',
    iosBundleId: 'y',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpjDmFt5aEJpfy5sBYhT2HIHc30T_zWXI',
    appId: '1:585335891737:ios:ef010c3f7592b004cd0788',
    messagingSenderId: '585335891737',
    projectId: 'bismillahh-3650a',
    storageBucket: 'bismillahh-3650a.appspot.com',
    iosBundleId: 'y',
  );
}
